#!/usr/bin/env bash

install_rvm()
{
    if [ ! -x ~/.rvm ]; then 
      bash -s stable --ruby < <(curl -L https://get.rvm.io)
    fi
    mkdir ~/.rvm/gemsets/
    source $HOME/.rvm/scripts/rvm
    cp ~/repositories/developwithpassion/devtools/shared/dotfiles/rvm/global.gems ~/.rvm/gemsets/
    rvm reload
    rvm get head
    rvm reload
}

install_rvm
