#!/usr/bin/env ruby

bprove = File.expand_path(File.join(File.dirname(__FILE__),'bprove'))

file_names = ARGV[0]
lib = File.basename(Dir.pwd)
file_names ||= "proofs/#{lib}.rb"
file_names = File.expand_path(file_names)

file_names = File.join(file_names,"**/*.rb") if (Dir.exist?(file_names))
puts "The file path is #{file_names} ---"

system("#{bprove} #{file_names}")


