#!/usr/bin/env ruby

require_relative 'colours'
require_relative 'text_effects'
require_relative 'coloured_text'
require_relative 'line_processor'
require_relative 'line_formatters'
require_relative 'matchers'
require_relative 'runner'

include Proof::Runner


run



